# Generated by Django 5.1.15 on 2026-05-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceupload',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
