# Generated by Django 5.1.15 on 2026-05-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_backfill_library'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvidenceUpload',
        ),
    ]
