# Generated by Django 5.1.15 on 2026-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_questionnaire_distributed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='is_numeric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criterion',
            name='numeric_fields',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='response',
            name='numeric_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
