# Generated by Django 5.1.15 on 2026-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_numeric_criterion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcategory',
            name='is_informal_sector_only',
            field=models.BooleanField(default=False),
        ),
    ]
