# Generated by Django 5.1.15 on 2026-09-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_judging_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='judging_comments',
            field=models.TextField(blank=True, default='', help_text='Overall comments provided by the Judge.'),
        ),
    ]
