# Generated by Django 5.1.15 on 2026-09-21 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_judge_excel_attachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='judgeresponse',
            new_name='assessment__questio_dae775_idx',
            old_name='assessment_judge_questio_8c1f1f_idx',
        ),
        migrations.RenameIndex(
            model_name='judgeresponse',
            new_name='assessment__judge_i_38974c_idx',
            old_name='assessment_judge_judge_id_1e9f5a_idx',
        ),
    ]
