# Generated by Django 5.1.15 on 2026-05-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='investment_capital',
            field=models.CharField(blank=True, choices=[('up_to_5m', 'Up to 5 Million'), ('5m_to_200m', '5 Million – 200 Million'), ('200m_to_800m', '200 Million – 800 Million'), ('above_800m', 'Above 800 Million')], max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='num_employees',
            field=models.CharField(blank=True, choices=[('1_4', '1 – 4'), ('5_49', '5 – 49'), ('50_99', '50 – 99'), ('100_plus', '100+')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(blank=True, choices=[('government_agency', 'Government Agency'), ('private', 'Private Organization'), ('ngo', 'NGO'), ('locally_owned', 'Locally Owned Organization')], max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='physical_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
