# Generated by Django 5.1.15 on 2026-05-14 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_extend_organization_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_name", models.CharField(max_length=255)),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("government_agency", "Government Agency"),
                            ("private", "Private Organization"),
                            ("ngo", "NGO"),
                            ("locally_owned", "Locally Owned Organization"),
                        ],
                        max_length=50,
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("physical_address", models.TextField()),
                ("postal_address", models.CharField(max_length=255)),
                (
                    "num_employees",
                    models.CharField(
                        choices=[
                            ("1_4", "1 – 4"),
                            ("5_49", "5 – 49"),
                            ("50_99", "50 – 99"),
                            ("100_plus", "100+"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "investment_capital",
                    models.CharField(
                        choices=[
                            ("up_to_5m", "Up to 5 Million"),
                            ("5m_to_200m", "5 Million – 200 Million"),
                            ("200m_to_800m", "200 Million – 800 Million"),
                            ("above_800m", "Above 800 Million"),
                        ],
                        max_length=50,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
