# Generated by Django 5.1.15 on 2026-05-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationrequest',
            name='position',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(blank=True, choices=[('government_agency', 'Government Agency'), ('private', 'Private Organization'), ('ngo', 'NGO'), ('informal_sector', 'Informal Sector')], max_length=50),
        ),
        migrations.AlterField(
            model_name='participationrequest',
            name='org_type',
            field=models.CharField(choices=[('government_agency', 'Government Agency'), ('private', 'Private Organization'), ('ngo', 'NGO'), ('informal_sector', 'Informal Sector')], max_length=50),
        ),
    ]
