# Generated by Django 5.1.15 on 2026-06-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_position_and_informal_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_subtype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_subtype_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='participationrequest',
            name='org_subtype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participationrequest',
            name='org_subtype_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(blank=True, choices=[('public_administration', 'Public Administration and Government Services'), ('mining_extraction', 'Mining/Extraction'), ('manufacturing', 'Manufacturing Industries'), ('financial_services', 'Financial Services'), ('insurance', 'Insurance Services'), ('tourism_hospitality', 'Tourism and Hospitality'), ('transportation_logistics', 'Transportation, Logistics and Storage'), ('ict', 'Information Communication Technology'), ('health_social', 'Health and Social Services'), ('education_vocational', 'Education and Vocational Training'), ('construction', 'Construction and Land Development'), ('real_estate_property', 'Real Estate and Property Services'), ('energy', 'Energy'), ('ngos', 'NGOs'), ('agriculture_agribusiness', 'Agriculture & Agri Business'), ('trade_commerce', 'Trade and Commerce'), ('professional_services', 'Professional Services'), ('sports_recreation_creative', 'Sports, Recreation, Creative and Cultural Industries'), ('environmental_green', 'Environmental and Green Economy'), ('informal_sector', 'Informal Sector')], max_length=50),
        ),
        migrations.AlterField(
            model_name='participationrequest',
            name='org_type',
            field=models.CharField(choices=[('public_administration', 'Public Administration and Government Services'), ('mining_extraction', 'Mining/Extraction'), ('manufacturing', 'Manufacturing Industries'), ('financial_services', 'Financial Services'), ('insurance', 'Insurance Services'), ('tourism_hospitality', 'Tourism and Hospitality'), ('transportation_logistics', 'Transportation, Logistics and Storage'), ('ict', 'Information Communication Technology'), ('health_social', 'Health and Social Services'), ('education_vocational', 'Education and Vocational Training'), ('construction', 'Construction and Land Development'), ('real_estate_property', 'Real Estate and Property Services'), ('energy', 'Energy'), ('ngos', 'NGOs'), ('agriculture_agribusiness', 'Agriculture & Agri Business'), ('trade_commerce', 'Trade and Commerce'), ('professional_services', 'Professional Services'), ('sports_recreation_creative', 'Sports, Recreation, Creative and Cultural Industries'), ('environmental_green', 'Environmental and Green Economy'), ('informal_sector', 'Informal Sector')], max_length=50),
        ),
    ]
