# Generated by Django 5.1.15 on 2026-09-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('verifier', 'Verifier'), ('judge', 'Judge')], max_length=20),
        ),
    ]
