# Generated by Django 5.1.15 on 2026-09-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_secretariat_role_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='requires_judging',
            field=models.BooleanField(default=False, help_text='If enabled, this organization follows Member → Secretariat → Judges → Final Results.'),
        ),
    ]
