# Generated by Django 5.1.15 on 2026-05-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_add_auditlog_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('request.approved', 'Request Approved'), ('request.rejected', 'Request Rejected'), ('cycle.opened', 'Cycle Opened'), ('cycle.closed', 'Cycle Closed'), ('user.created', 'User Created'), ('user.deleted', 'User Deleted'), ('user.edited', 'User Edited'), ('org.created', 'Organization Created'), ('org.deleted', 'Organization Deleted'), ('questionnaire.submitted', 'Questionnaire Submitted'), ('verifier.scores_saved', 'Verifier Scores Saved')], max_length=50),
        ),
    ]
