# Generated by Django 5.1.15 on 2026-07-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('request.approved', 'Request Approved'), ('request.rejected', 'Request Rejected'), ('request.reopened', 'Request Reopened'), ('cycle.opened', 'Cycle Opened'), ('cycle.closed', 'Cycle Closed'), ('user.created', 'User Created'), ('user.deleted', 'User Deleted'), ('user.edited', 'User Edited'), ('org.created', 'Organization Created'), ('org.deleted', 'Organization Deleted'), ('questionnaire.submitted', 'Questionnaire Submitted'), ('verifier.scores_saved', 'Verifier Scores Saved'), ('report.distributed', 'Report Distributed'), ('report.revoked', 'Report Revoked'), ('sharelink.created', 'Share Link Created'), ('sharelink.revoked', 'Share Link Revoked')], max_length=50),
        ),
    ]
